### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zych1751** [zych1751/Blog#1]
- [x] 게시글에 카테고리 추가

- [x] 카테고리별 탐색기

- [x] admin 페이지 디자인

- [x] 글 목록 페이징

- [x] admin 페이지에서 삭제할때 한번 물어보기

- [ ] 회원가입 + 댓글

- [x] 게시글에 사진 추가

- [x] 동영상 추가 ( 마크다운 안에선 유튜브 동영상은 직접 삽입 불가 다른방법을 찾아야함)

- [x] 글쓰기 창에서 나가려고 할 때, 삭제할때 한번 더 물어보기 ㅂㄷㅂㄷ

- [x] 게시물 코드 하이라이트

- [x] 보안 인증서 추가

- [x] 게시글에서 이미지가 본문 밖으로 벗어나는거 처리

**Comment by zych1751** [comment]
회원 관련 기능 구현 안할 예정
