### ISSUE TITLE
TODO v2

### ISSUE THREAD

**Issue by zych1751** [zych1751/Blog#6]
- [ ] graphQL

- [ ] 나 소개 페이지 하나도 만들자

- [ ] 조회수

- [ ] 도커를 사용해보자

- [ ] 트래비도 사용해보자

- [ ] 검색 기능

- [ ] lint

- [ ] typescript

- [ ] presentational, continaer component 패턴 도입

- [ ] 테스팅(mocha)

- [ ] 어드민 페이지 디자인

- [ ] 어드민 페이지 postedit 페이징

- [ ] Post에 대해서 내용 미리보기 만들기

- [ ] Post의 디자인 수정(폰트, 글자 간격)

- [ ] 코드 하이라이팅 바꾸기

- [ ] SSR
